### ISSUE TITLE
Documentation or examples

### ISSUE THREAD

**Issue by hskang9** [polkascan/polkascan-pre-explorer-api#1]
Hello @arjanz, Is there an example to test the api or the working endpoint to use this?
It would be great if there is an Documentation for the api as well.

**Comment by emielsebastiaan** [comment]
Please check this blog post: https://medium.com/polkadot-network/polkascan-development-update-3-fdea45ab959f

**Comment by hskang9** [comment]
Thank you sir, I will look into it.

**Comment by dillu24** [comment]
I am trying to follow the quick deployment guide of polkascan. However when running the UI I am not getting data. 

Do I need to run the full deployment for it to get the data?

Is there are way I can access the API?
