### ISSUE TITLE
Questions: public API, additional features

### ISSUE THREAD

**Issue by jsamol** [polkascan/polkascan-pre-explorer-api#5]
Hi,
I have a couple of questions regarding the API:
- Is the API exposed somewhere that can be queried from public? If no, when can we expect to have it available?
- Are you planning on adding features such as paging or filtering by the account id, especially for the `/transfer` endpoint? (Based on [this](https://medium.com/polkadot-network/polkascan-development-update-3-fdea45ab959f) article I'm assuming they haven't been implemented yet)

Thanks!

**Comment by emielsebastiaan** [comment]
Hi @jsamol 
We have no immediate plans to service public API endpoints.
You can run the Polkascan stack yourself to make the API available.
I suggest you checkout Development Update 4: https://medium.com/polkadot-network/polkascan-development-update-4-584705a00cc6

Our current grant work will cover account based enhancements of the Polkascan stack. We expect to finish that within two months from today. You can find out more about the details here: https://github.com/w3f/General-Grants-Program/blob/master/grants/speculative/polkascan_account_module.md
